emc-openstack/storops

storops/exception.py, storops/lib/resource.py, storops/unity/resource/port.py, test-requirements.txt, test/unity/resource/test_port.py, test/unity/rest_data/ethernetPort/index.json, test/unity/rest_data/ethernetPort/spa_eth3.json, test/unity/rest_data/ethernetPort/spb_eth3.json, test/unity/rest_data/ethernetPort/type.json
Supports modifying the speed and mtu of the ethernet ports on unity system
=> [GH-22] Unity ethernet port modification support

storops/lib/resource.py, storops/unity/client.py, storops/unity/parser.py, storops/unity/resource/__init__.py, storops/unity/resource/host.py, storops/unity/resource/port.py, test/unity/resource/test_host.py, test/unity/resource/test_port.py, test/unity/rest_data/host/all.json, test/unity/rest_data/host/host_1.json, test/unity/rest_data/host/host_10.json, test/unity/rest_data/host/host_12.json, test/unity/rest_data/host/host_9.json, test/unity/rest_data/host/index.json, test/unity/rest_data/iscsiPortal/if_4.json, test/unity/rest_data/iscsiPortal/index.json, test/unity/rest_data/iscsiPortal/type.json, test/unity/test_parser.py
Support nested properties query to enhance performance
=> [GH-32] Support nested properties query for Unity

storops/unity/enums.py, storops/unity/resource/system.py, test/unity/resource/test_port.py, test/unity/resource/test_system.py, test/unity/rest_data/fcPort/all.json, test/unity/rest_data/fcPort/index.json, test/unity/rest_data/fcPort/spa_fc4.json, test/unity/rest_data/fcPort/type.json
Adds a new API get_fc_port in class UnitySystem to get all the fc
ports of the system.
=> [GH-30] Add fc port list support

README.rst, storops/unity/resource/port.py, storops/unity/resource/system.py, test/unity/resource/test_system.py, test/unity/rest_data/ioLimitPolicy/index.json, test/unity/rest_mock.py
Add list and create entry point for `UnityIoLimitPolicy` on `UnitySystem`.
=> [GH-36] UnityIoLimitPolicy entry on UnitySystem

requirements.txt, storops/exception.py, storops/lib/resource.py, storops/lib/tasks.py, storops/vnx/nas_client.py, storops/vnx/resource/mirror_view.py, storops/vnx/resource/system.py, test/lib/test_tasks.py, test/vnx/resource/test_mirror_view.py, test/vnx/resource/test_nas_client.py
With the support of this commit, user can:
* add storops operations to a queue, and they can be executed periodically till
operation executes correctly.
* unfinished items in the queue can be restored automatically after restart.
=> [GH-46]Support persistent queue for storops

storops/__init__.py, test/__init__.py
Add an API on storops module to enabled and disable the console logging
=> [GH 59] Enable/disable console logging

storops/exception.py, storops/lib/resource.py, storops/unity/resource/port.py, storops/unity/resource/tenant.py, test/lib/test_metric.py, test/lib/test_resource.py, test/unity/resource/test_nas_server.py, test/unity/resource/test_port.py, test/unity/resource/test_system.py, test/unity/resource/test_tenant.py, test/unity/rest_data/ethernetPort/all.json, test/unity/rest_data/ethernetPort/index.json, test/unity/rest_data/host/index.json, test/unity/rest_data/nasServer/index.json, test/unity/rest_data/nasServer/nas_server_in_tenant2.json, test/unity/rest_data/tenant/delete_tenant.json, test/unity/rest_data/tenant/index.json, test/unity/rest_data/tenant/tenant_2.json, tox.ini
Adds API on the tenant object to delete tenant along with its hosts.
=> [GH-72] Tenant delete enhancement

README.rst, requirements.txt, storops/lib/tasks.py, test/lib/test_tasks.py
persist-queue supports more platforms
and queuelib is not very active, so switch to persist-queue for now.
=> Use persist-queue instead of queuelib

.travis.yml, README.rst, circle.yml
Add codecov as coverage report vendor.
=> Add codecov CI

MANIFEST.in, README.rst, appveyor.yml, storops_test/lib/test_tasks.py
Add appveyor as the CI vendor.
=> Add Windows CI support

README.rst, setup.py
The `packages` should use the find_packages to automatically package
required files.
=> Use find_packages to package

storops/exception.py, storops/lib/converter.py, storops/vnx/block_cli.py, storops/vnx/enums.py, storops/vnx/parser_configs.yaml, storops/vnx/resource/mirror_view.py, storops/vnx/resource/system.py, storops_test/vnx/resource/test_mirror_view.py, storops_test/vnx/resource/test_system.py, storops_test/vnx/testdata/block_output/mirror_-sync_-addtogroup_-name_petermg_-mirrorname_mv0.txt, storops_test/vnx/testdata/block_output/mirror_-sync_-creategroup_-name_test_group_in_use_-recoverypolicy_auto_-o.txt, storops_test/vnx/testdata/block_output/mirror_-sync_-listgroups.txt, storops_test/vnx/testdata/block_output/mirror_-sync_-listgroups_-name_petermg.txt, storops_test/vnx/testdata/block_output/mirror_-sync_-listgroups_-name_petermg1.txt, storops_test/vnx/testdata/block_output/mirror_-sync_-listgroups_-name_test_group.txt, storops_test/vnx/testdata/block_output/mirror_-sync_-removefromgroup_-name_petermg_-mirrorname_not_in_group_-force_-o.txt, storops_test/vnx/testdata/block_output/mirror_-sync_-syncgroup_-name_mg_promote_on_primary.txt
Add following functionalities in storops:
* Create mirror group
* Add mirrorview to group
* Delete mirror group
* Sync/fracture/promote mirror group
* Get mirror group
=> [GH-122]Add VNX MirrorView group support

storops/connection/client.py, storops/unity/client.py, storops/unity/resource/system.py, storops_test/connection/test_client.py, storops_test/unity/resource/test_system.py, storops_test/unity/rest_data/index.json, storops_test/unity/rest_mock.py
Add `UnitySystem.upload_license` interface for installing license
for Unity array.
=> [GH-131]Add upload_license for Unity array

utility/rpm_publish/storops_rpm.spec
Update the rpm spec file and generate rpm package for version 0.4.13.
=> [GH-138] Release RPM package v0.4.13

README.rst, storops/lib/converter.py, storops/unity/parser_configs.yaml, storops/unity/resource/host.py, storops/unity/resource/lun.py, storops/unity/resource/pool.py, storops/unity/resource/port.py, storops/unity/resource/system.py, storops_test/lib/test_converter.py, storops_test/unity/resource/test_host.py, storops_test/unity/resource/test_lun.py, storops_test/unity/resource/test_port.py, storops_test/unity/rest_data/host/index.json, storops_test/unity/rest_data/hostInitiator/index.json, storops_test/unity/rest_data/hostInitiator/initiator_19.json, storops_test/unity/rest_data/hostInitiator/initiator_4.json, storops_test/unity/rest_data/ioLimitPolicy/index.json, storops_test/unity/rest_data/lun/sv_2.json, storops_test/unity/rest_data/storageResource/index.json
Fixed following issue:
* Remove is_thin from Lun.modify since Unity cannot modify it
* Add is_compression when creating new LUN.
* Add update_initiators for UnityHost
* Add update_hosts for UnityLun
=> Fix lun creation nits

README.rst, circle.yml, setup.py, storops/unity/parser_configs.yaml, storops/unity/resource/pool.py, storops_test/unity/resource/test_pool.py, storops_test/unity/rest_data/pool/index.json
This will allow for pool modification and expansion.
=> [GH-157]Add modify for UnityPool

storops/unity/enums.py
Add below enums:
- `DiskTypeEnum`
- `DiskTechnologyEnum`
=> [GH-164]Add enums for SAS_FLASH_4

README.rst, storops/vnx/parser_configs.yaml, storops/vnx/parsers.py, storops/vnx/resource/block_pool.py, storops_test/vnx/resource/test_block_pool.py, storops_test/vnx/testdata/block_output/storagepool_-list_-all_-name_tier_test.txt
Add information for each tier of a certain VNX pool
=> [GH-162]Add tier information for storage pool

storops/exception.py, storops/vnx/block_cli.py, storops/vnx/resource/lun.py, storops/vnx/resource/snap.py, storops_test/vnx/resource/test_snap.py, storops_test/vnx/testdata/block_output/snap_-restore_-id_s5_-res_540_-bakName_a-existing-snap.txt, storops_test/vnx/testdata/block_output/snap_-restore_-id_s5_-res_541.txt
Add `restore_snapshot` support to VNX.
=> [GH-179] Revert snapshot to volume

storops/unity/resource/lun.py, storops_test/unity/resource/test_lun.py, storops_test/unity/rest_data/lun/index.json, storops_test/unity/rest_data/lun/sv_5.json, storops_test/unity/rest_data/storageResource/index.json
Update `detach_from` API of lun to support detaching the lun from all
hosts.
=> [GH-186] Add support to detach all on lun

storops/unity/resource/host.py, storops_test/unity/rest_data/hostIPPort/index.json
fix the bug when ipv6 prefix is None.
=> fix the bug when ipv6 prefix is None

storops/vnx/resource/sg.py, storops_test/vnx/resource/test_sg.py
Under certain circumstances, the alu/hlu cache was flushed by an
sg.update(), thus the detach of the alu was skipped as not found
in the cache.
An unbind LUN error will be thrown when deleting the LUN:
Cannot unbind LUN because it's contained in a Storage Group
This commit will update the cache incrementally when calling
sg.update, addtionally more logs are added around the cache for
later triage.
=> Fix alu/hlu cache issue

storops/exception.py, storops/unity/resource/host.py, storops_test/unity/resource/test_host.py, storops_test/unity/rest_data/host/host_22.json, storops_test/unity/rest_data/host/host_23.json, storops_test/unity/rest_data/host/host_24.json, storops_test/unity/rest_data/host/host_25.json, storops_test/unity/rest_data/host/host_26.json, storops_test/unity/rest_data/host/index.json, storops_test/unity/rest_data/host/modify_host_lun_hlu_in_use.json, storops_test/unity/rest_data/lun/index.json, storops_test/unity/rest_data/lun/sv_5609.json, storops_test/unity/rest_data/lun/sv_5610.json, storops_test/unity/rest_data/lun/sv_5611.json, storops_test/unity/rest_data/lun/sv_5612.json, storops_test/unity/rest_data/storageResource/index.json
- First attach the LUN, then modify HLU if it's 0.
- Detach the dummy lun which was attached via legacy storops.
=> Modify HLU if it's 0 and detach legacy dummy LUN

utility/osp_deploy.sh
This commit adds selinux relabel, so that it will not fail during
the boot time.
=> add selinux relabel.

utility/osp_deploy.sh
Get persist-queue, cachez, retryz rpm packages from emc-openstack/packages repo.
=> Update rpm package urls in osp_deploy.sh

storops/exception.py, storops/unity/resource/cg.py, storops/unity/resource/host.py, storops/unity/resource/lun.py, storops/unity/resource/snap.py, storops_test/unity/resource/test_cg.py, storops_test/unity/resource/test_host.py, storops_test/unity/resource/test_lun.py, storops_test/unity/rest_data/host/host_27.json, storops_test/unity/rest_data/host/index.json, storops_test/unity/rest_data/lun/index.json, storops_test/unity/rest_data/lun/sv_58.json, storops_test/unity/rest_data/snap/38654705831.json, storops_test/unity/rest_data/snap/85899345958.json, storops_test/unity/rest_data/snap/filter_member_snap_sv_58.json, storops_test/unity/rest_data/snap/index.json, storops_test/unity/rest_data/storageResource/delete_sv_5605_with_thin_clone.json, storops_test/unity/rest_data/storageResource/index.json, storops_test/unity/rest_data/storageResource/res_21.json, storops_test/unity/rest_data/storageResource/sv_8.json, storops_test/unity/rest_data/storageResource/sv_9.json
- `update_lun` accepts `add_luns` and `remove_luns` to update the luns
in cg.
- Update host.attach to attach a member snap of cg snap.
=> Unity: add cg.update_lun and attach member snap

.travis.yml, appveyor.yml, storops/exception.py, storops/lib/common.py, storops/lib/converter.py, storops/lib/parser.py, storops/unity/client.py, storops/unity/resource/__init__.py, storops/unity/resource/cifs_server.py, storops/unity/resource/cifs_share.py, storops/unity/resource/filesystem.py, storops/unity/resource/job.py, storops/unity/resource/lun.py, storops/unity/resource/nas_server.py, storops/unity/resource/nfs_server.py, storops/unity/resource/nfs_share.py, storops/unity/resource/snap.py, storops/vnx/resource/disk.py, storops/vnx/resource/vdm.py, storops_test/unity/resource/test_filesystem.py, storops_test/unity/resource/test_job.py, storops_test/unity/resource/test_nfs_share.py, storops_test/vnx/resource/test_cifs_share.py, tox.ini
Major changes:
* In Python3.7, 'async' become reserved keyword, so change parameter
name from 'async' to 'async_mode' in related interfaces.
* Fix pep8 issues to suit new flake8 version.
* Enable Python3.7 test in AppVeyor
=> [GH-244] Fix pep8 issues

storops/unity/resource/lun.py, storops_test/unity/resource/test_move_session.py, storops_test/unity/rest_data/moveSession/create_move_35.json, storops_test/unity/rest_data/moveSession/index.json, storops_test/unity/rest_data/moveSession/move_35.json
Support changing thin/thick, data_reduction in volume migration for cinder retype user story
=> support change thin/thick, data_reduction in migration

requirements.txt, storops/exception.py, storops/unity/enums.py, storops/unity/parser_configs.yaml, storops/unity/resource/alert_config_snmp.py, storops/unity/resource/system.py, storops_test/unity/resource/test_alert_config_snmp.py, storops_test/unity/resource/test_system.py, storops_test/unity/rest_data/alertConfigSNMPTarget/all.json, storops_test/unity/rest_data/alertConfigSNMPTarget/create_invalid.json, storops_test/unity/rest_data/alertConfigSNMPTarget/filter_ip.json, storops_test/unity/rest_data/alertConfigSNMPTarget/index.json, storops_test/unity/rest_data/alertConfigSNMPTarget/snmp_target_3.json, storops_test/unity/rest_data/alertConfigSNMPTarget/snmp_target_4.json, storops_test/unity/rest_data/alertConfigSNMPTarget/snmp_target_5.json, storops_test/unity/rest_data/alertConfigSNMPTarget/snmp_target_8.json, storops_test/unity/rest_data/alertConfigSNMPTarget/snmp_target_9.json, storops_test/unity/rest_data/alertConfigSNMPTarget/type.json, storops_test/unity/rest_data/alertConfigSNMPTarget/v2_create.json, storops_test/unity/rest_data/alertConfigSNMPTarget/v3_create.json, tox.ini
-Collection query
-Instance query
-Create
-Delete
-Modify
=> Add Unity supported operations for alert SNMP configurations:

storops/unity/resource/nas_server.py, storops_test/unity/resource/test_nas_server.py, storops_test/unity/rest_data/nasServer/index.json
=> Unity: support NAS server 'modify'

storops/unity/enums.py
=> Unity: update NasServerUnixDirectoryServiceEnum

storops/unity/parser_configs.yaml, storops/unity/resource/cifs_server.py, storops/unity/resource/nas_server.py, storops/unity/resource/nfs_server.py, storops/unity/resource/system.py, storops_test/unity/resource/test_cifs_server.py, storops_test/unity/resource/test_nfs_server.py, storops_test/unity/resource/test_system.py, storops_test/unity/rest_data/cifsServer/cifs_5.json, storops_test/unity/rest_data/cifsServer/index.json, storops_test/unity/rest_data/nfsServer/index.json, storops_test/unity/rest_data/nfsServer/nfs_4.json, storops_test/unity/rest_mock.py
Major changes:
- Supports modification of NFS/CIFS server
- Supports modification of virus checker
- Supports file uploading/downloading for NAS server
=> Unity: supports modification of NFS/CIFS server

storops/connection/client.py
=> Fix Checkmarx Issues
