emc-openstack/storops

- storops/exception.py
- storops/unity/resource/__init__.py
- storops/unity/resource/host.py
- storops/unity/resource/system.py
- storops/unity/resp.py
- test/test_exception.py
- test/unity/resource/test_system.py
* Fix UnityResourceList.get will return fake object issue.
* Fix system.get_iscsi_portal since there is no 'name' property at all
* Make UnityNameNotUniqueError can return the found objects
> Fix UnityResourceList.first_item issue of host.add_initiator and system.create_host

- README.rst
- storops/vnx/enums.py
- storops/vnx/resource/port.py
- test/vnx/resource/test_port.py
Add property `display_name` to VNXPort and VNXSPEnum.
If you have an `VNXPort` instance, let's say `port`.
Then `port.display_name` will return a string like 'A-0-0' for iSCSI and 'A-1' for FC.
> [GH-10] add display name to vnx port

- storops/vnx/resource/vnx_domain.py
- test/vnx/resource/test_vnx_domain.py
When user retrieves the property of a VNX system, an error pops up saying
this vnx node cannot be found in the domain.
It should not be an error because it's a normal configuration.  Use an
info log instead.
When this happens, the control station IP won't be available.
> [GH-17] Error if vnx domain not configured

- README.rst
- storops/vnx/navi_command.py
- test/vnx/test_navi_command.py
Currently, it is impossible to use the VNX driver in cinder (master branch) with a security file, whereas the old driver (for stable/mitaka) used to work well.
The cause of the issue is as follows
* Storops side:
* **username** and **password** currently take precedence over **sec_file** if both are defined (*defined* meaning different from None).
* Cinder side:
* **san_login** and **san_password** have default values (`'admin'` and `''`, respectively):  [cinder/volume/drivers/san/san.py:45](https://github.com/openstack/cinder/blob/9567844f0e180a7278767fdcd4378b19913933be/cinder/volume/drivers/san/san.py#L45)
* **storage_vnx_security_file_dir** does not have a default value: [cinder/volume/drivers/emc/vnx/common.py:46](https://github.com/openstack/cinder/blob/572b84c073ef66d976d4530d9b7f07 …
> Prefer security file over username/password

- storops/exception.py
- storops/unity/resource/lun.py
- test/unity/resource/test_lun.py
- test/unity/rest_data/storageResource/does_not_support_shrink.json
- test/unity/rest_data/storageResource/index.json
- test/unity/rest_data/storageResource/nothing_to_modify.json
Support expansion of Unity LUN.
Shrink is not supported.
Add error code for situations when new size is:
- smaller than current size.
- equal to current size.
> [GH-38] UnityLun expand support.

- storops/exception.py
- storops/vnx/resource/lun.py
- storops/vnx/resource/snap.py
Add keep_for parameter in lun.create_snap and snap.create interfaces
> Add missing keep_for parameter for snap operations

- storops/vnx/xmlapi.py
- test-requirements.txt
- test/vnx/nas_mock.py
- tox.ini
- Remove cobertura-clover-transform from test-requirements.
- Remove lxml dependency from VNX file UT.
> [GH-76] Remove cobertura and lxml dependency

- storops/lib/resource.py
- storops/unity/resource/__init__.py
- storops/unity/resource/nas_server.py
- storops/unity/resource/system.py
- storops/vnx/resource/__init__.py
- test/unity/resource/test_nas_server.py
- test/unity/resource/test_system.py
- test/unity/rest_data/nasServer/auto_balance_sp_one_sp.json
- test/unity/rest_data/nasServer/auto_balance_sp_to_spa.json
- test/unity/rest_data/storageProcessor/auto_balance_sp_one_sp.json
- test/unity/rest_data/storageProcessor/auto_balance_sp_to_spa.json
The current implementation is that: if SP is not passed in (is None) to
create NAS server, storops will use the first item of SP list.
This feature is to auto balance the SP of creating NAS server when SP
is not passed in. SPB will be chosen only when the existing NAS servers
on SPA are more than the ones on SPB. Otherwise, SPA will be chosen.
> [GH-74] Auto balance SP to create NAS server

- .travis.yml
- requirements.txt
- setup.py
- tox.ini
Add python 3.6 check for CI and tox.
Fix following issue:
* The `enum34` package creates dependency errors on python 3.6 due to the missing of `IntFlag`.
Change `setup.py` to only include this package when the python version is lower than 3.4.
> [GH-78] Python 3.6 Support

- storops/lib/resource.py
- storops/unity/resource/port.py
- storops/unity/resource/system.py
- test/unity/resource/test_port.py
- test/unity/resource/test_system.py
Add and an API get file port to return ethernet port and link aggregations.
For pre-Falcon release, only return ethernet ports.
> [GH 82] Get file port

- .gitattributes
- README.rst
- storops/vnx/parser_configs.yaml
- test/vnx/resource/test_sg.py
- test/vnx/testdata/block_output/storagegroup_-messner_-list_-host_-iscsiAttributes_-gname_a.b.c.txt
When the HBA uid is too long, the table format of storage group output
is messed up.  There is no space between each column.
Luckly, the format for storage processor is fixed.  We could use it as the
token.  Modify the regular expression to parse the HBA and verify the
parsing of storage group with the messed output.
Bump the version to 0.4.4.
> [GH-84] Error parsing VNX storage group output.

- storops/exception.py
- storops/vnx/resource/migration.py
- test/vnx/resource/test_migration.py
- test/vnx/testdata/block_output/migrate_-cancel_-source_1_-o.txt
When cancelling migration, a error message may come out:
Migration cannot be cancelled because data sychronization is completed
(0x714a8021)
This is to add a VNXLunSyncCompletedError to differentiate it from
general error.
> [GH-87]Add VNXLunSyncCompletedError for migration

- storops/unity/resource/host.py
- storops/unity/resource/snap.py
Attaching snap to host only supports from Unity OE version 4.1.
Although before the version 4.1, attaching snap to host would succeed,
the IO to the snap will fail.
We need to add version check to only allow attaching snap to host in
version 4.1 or later.
> [GH-90] Unity:Check version for attaching snap

- README.rst
- storops/unity/parser_configs.yaml
- storops/unity/resource/port.py
- storops_test/unity/resource/test_port.py
- storops_test/unity/rest_data/ethernetPort/index.json
- storops_test/unity/rest_data/ethernetPort/spa_iom_0_eth0.json
For ports on IO modules, there is no property
`parent_storage_processor`. Set it manually with the value of property
`storage_processor`
> GH-99 Set property `parent_storage_processor`

- storops/exception.py
- storops/lib/common.py
- storops/lib/converter.py
- storops/lib/resource.py
- storops/vnx/block_cli.py
- storops/vnx/enums.py
- storops/vnx/parser_configs.yaml
- storops/vnx/resource/nqm.py
- storops/vnx/resource/system.py
- storops_test/lib/test_common.py
- storops_test/vnx/resource/test_lun.py
- storops_test/vnx/resource/test_nqm.py
- storops_test/vnx/resource/test_system.py
- storops_test/vnx/test_block_cli.py
- storops_test/vnx/test_enums.py
- storops_test/vnx/testdata/block_output/nqm_-ioclass_-list.txt
- storops_test/vnx/testdata/block_output/nqm_-ioclass_-list_-name_running_ioclass.txt
- storops_test/vnx/testdata/block_output/nqm_-ioclass_-list_-name_simple.txt
- storops_test/vnx/testdata/block_output/nqm_-ioclass_-list_-name_with_3_luns.txt
- storops_test/vnx/testdata/block_output/nqm_-ioclass_-list_-name_with_luns_snaps.txt
- storops_test/vnx/testdata/block_output/nqm_-ioclass_-modify_-name_running_ioclass_-luns_1_-o.txt
- storops_test/vnx/testdata/block_output/nqm_-policy_-list.txt
- storops_test/vnx/testdata/block_output/nqm_-policy_-list_-name_new_name_test.txt
- storops_test/vnx/testdata/block_output/nqm_-policy_-list_-name_new_policy.txt
- storops_test/vnx/testdata/block_output/nqm_-policy_-list_-name_running_policy.txt
- storops_test/vnx/testdata/block_output/nqm_-policy_-list_-name_with_ioclass.txt
- storops_test/vnx/testdata/block_output/nqm_-policy_-modify_-name_running_policy_-ioclasses_simple_with_luns_snaps.txt
- tox.ini
* Add VNXIOClass and related operations
* Add VNXIOPolicy and related operations
> [GH-94]Add VNX QoS support

- storops/vnx/navi_command.py
Logging should be do in the same thread of the caller instead of
the newly created thread.
> [GH-102] Perserve thread local info when logging

- MANIFEST.in
- storops/lib/resource.py
- storops_test/vnx/resource/test_cg.py
- storops_test/vnx/testdata/block_output/snap_-group_-list_-id_another cg_-detail.txt
- storops_test/vnx/testdata/block_output/snap_-group_-list_-id_test cg name_-detail.txt
The resource list class doesn't update the internal property `_name` or
`_id` of the resource instance.  When a resource instance within the
resource list tries to update itself, it couldn't find the unique key for
itself.
Fix part of the issue by assigning `name` to `_name` during updates.
> [GH-96] Update list members error.

- storops/unity/resource/system.py
- storops_test/unity/resource/test_system.py
- storops_test/unity/rest_data/ethernetPort/index.json
- storops_test/unity/rest_data/ethernetPort/unbond_ethernet_ports.json
The bond port is port that has been added to link aggregation. The
get_file_port should not return them because the bond port can not
be used to create interfaces.
> [GH-108] Not return bond ether port in get_file_port

- storops/lib/common.py
- storops/unity/resource/filesystem.py
- storops/unity/resource/job.py
- storops/unity/resource/pool.py
- storops_test/lib/test_common.py
This patch adds extra capacity for filesystem metadata when user
specifies "user_cap=True" when creating/extending filesystem.
> Add supplement for the filesystem

- storops/exception.py
- storops_test/unity/resource/test_host.py
- storops_test/unity/rest_data/hostInitiator/index.json
- storops_test/unity/rest_data/hostInitiator/initiator_already_existed.json
This patch will raise UnityHostInitiatorExistedError when meets
below error:
The specified host initiator already exists. (Error Code:0x60000f3)
> [GH-114]Add a exception for initiator creation

- storops/exception.py
- storops/unity/client.py
- storops/unity/resource/type_resource.py
- storops_test/unity/resource/test_port.py
- storops_test/unity/resource/test_system.py
- storops_test/unity/rest_data/fcPort/fc_port_not_supported.json
- storops_test/unity/rest_data/linkAggregation/link_aggregation_not_supported.json
- storops_test/unity/rest_mock.py
When query UnityLinkAggregation or UnityFcPort on VSA, a exception will
be thrown. This fix will handle the 404 not found error and return an
empty list on any query for link aggregation or fc port.
> [GH-115]Fix incompatible issue with VSA

- README.rst
- storops/lib/common.py
- storops/unity/resource/host.py
- storops_test/lib/test_common.py
storops treats format for RedHat initiator as invalid, this causes
issue when creating HostInitiator.
Now, any initiator name starting with "iqn" will be treated as valid.
> [GH-118]Fix initiator issue for RH distro

- README.rst
- requirements.txt
- storops/connection/connector.py
- storops/lib/common.py
- storops_test/lib/test_common.py
The paramiko is now optional since it's not widely used in storops.
If user wants to manage VNX file resources, he could install paramiko.
This makes the installation of storops much more easier for most use
cases.
> [GH-123]Make paramiko as optional

- utility/rpm_publish/readme.md
- utility/rpm_publish/requirements.os.txt
- utility/rpm_publish/storops_rpm.spec
- Use only one `requirements.txt`.
- Download the pypi packages based on the `requirements.txt`.
- Install the packages using `pip find-links`, which will find packages under a directory and will not upgrade the installed packages.
> [GH-128] Enhance rpm packaging

- requirements.txt
In current implementation, storops depends on PyYAML >= 3.11.
However, the latest version of PyYAML in OSP10 is 3.10.
> [GH-147]Downgrade PyYAML dependence to 3.10

- appveyor.yml
- requirements.txt
The `requirements.txt` caused the UT failure.
Below line:
```
enum34;python_version=='2.7' or python_version=='2.6' or
python_version=='3.3' # BSD
```
Need to change it to:
```
enum34;python_version<'3.4' # BSD
```
> [GH-155]UT on python34 failed always

- storops/vnx/parser_configs.yaml
- storops/vnx/resource/nqm.py
- storops_test/vnx/resource/test_nqm.py
When adding/removing lun from ioclass, some unnecessary queries issued
against the VNX. The patch will only query the new luns information
instead of the existing ones.
> [GH-130]Remove redundent query from NQM modification

- storops/lib/parser.py
- storops/vnx/parser_configs.yaml
- storops/vnx/resource/port.py
- storops_test/vnx/resource/test_port.py
- storops_test/vnx/resource/test_system.py
- storops_test/vnx/testdata/block_output/connection_-getport_-all.txt
- storops_test/vnx/testdata/block_output/connection_-getport_-all_-sp_a_-portid_5_-vportid_2.txt
When multiple virtual ports are configured on each VNX port, the storops
only returns the first virtual port and ignore all the left ports due
to a parsing issue.
Additionally, This issue causes the Cinder failure when virtual
ports whose virtual port id is larger than zero are configured in
cinder.conf.
This fix provides a new object "VNXConnectVirtualPort" which provides
both port information as well as the virtual port information.
> [GH-171]Fix issue when parsing multiple virtual ports

- storops/vnx/parser_configs.yaml
- storops/vnx/resource/port.py
- storops_test/vnx/resource/test_port.py
- storops_test/vnx/resource/test_sg.py
- storops_test/vnx/test_parsers.py
- storops_test/vnx/testdata/block_output/storagegroup_-messner_-list_-host_-iscsiAttributes_-gname_ubuntu16.txt
Currently if multiple virtual ports are registerred on a storage group,
Only one virtual port can be fetch from sg.get_ports() due to a logic
filterring error.
This causes an incomplete port list returned to cinder, and a volume
attachment error may occurs.
> [GH-172]Registered ports are not returned from SG.

- storops/exception.py
- storops/unity/resource/host.py
- storops/unity/resource/storage_resource.py
- storops/vnx/resource/port.py
- storops_test/vnx/resource/test_lun.py
- storops_test/vnx/resource/test_port.py
- storops_test/vnx/resource/test_system.py
- storops_test/vnx/testdata/block_output/connection_-pingnode_-sp_a_-portid_5_-vportid_2_-address_192.168.1.50.txt
this patch fix following error when calling port.ping_node('ip')
AttributeError: 'VNXConnectionPort' does not contain attribute
'ping_node'
> Fix ping_node issue

- storops/unity/resource/snap.py
- storops_test/unity/resource/test_snap.py
- storops_test/unity/rest_data/snap/backup_response.json
- storops_test/unity/rest_data/snap/index.json
This commit adds a new parameter ``delete_backup`` to satisfy the
OpenStack Cinder driver requirement.
> Refine snap restore API for Unity

- storops/vnx/resource/sg.py
- storops_test/vnx/resource/test_sg.py
To support Cinder force detach volumes from all hosts, it needs to list
all the storage groups to which the specified LUN is attached.
> [GH-184]Add filter support to sg list

- storops/lib/converter.py
- storops_test/lib/test_converter.py
the host address can be '[2001:db8:a0b:12f0::/64]' and '2001:db8:a0b:12f0::/64'. This fix is for the ip address with []
> fix bug in parsing host id that are ipv6 enclosed with '[]'

- utility/osp_deploy.sh
- utility/rpm_publish/python-storops-vnx.spec
- utility/rpm_publish/python-storops.spec
The osp_deploy.sh doesn't work to deploy the storops rpm packages.
The old storops rpm contained all dependencies in it. But the new one
strip its dependencies out.
> Fix osp_deploy script

- storops/vnx/resource/port.py
- storops_test/vnx/resource/test_port.py
- storops_test/vnx/resource/test_system.py
- storops_test/vnx/testdata/block_output/connection_-getport_-all.txt
This commit add __hash__ for VNXConnectionVirtualPort so that
it can be compared with VNXHbaPort.
This issue causes duplicate port registration in VNX Cinder driver.
> Allow comparison of different port types

- utility/gen_yum_install.sh
This script will generate a self-extracting shell named
`yum_install_storops.sh` which contains the storops rpm package and its
dependency packages inside. Running it will use yum install all the
packages.
> Add script to generate install shell

- storops/unity/resource/snap.py
- storops_test/unity/resource/test_snap.py
- storops_test/unity/rest_data/snap/38654705670.json
- storops_test/unity/rest_data/snap/index.json
When attach an exported snapshot to another host, a error:
storops.exception.UnitySnapAlreadyPromotedException: The system was not
able to promote a snapshot because it is already promoted. (Error
Code:0x6000bdc)
will be throw. this commit will fix it by using the modify action
> [205]Fix issue for allowing snap host access.

- storops/unity/enums.py
- storops/unity/parser_configs.yaml
- storops/unity/resource/system.py
- storops_test/unity/resource/test_pool.py
- storops_test/unity/resource/test_system.py
Here are the enums updated in this patch:
- Unity 4.1:
* ConnectorTypeEnum
* EnclosureTypeEnum
* HostTypeEnum
* IOLimitPolicyStateEnum
* IOLimitPolicyTypeEnum
* JobTaskStateEnum
* MetricTypeEnum
* NasServerUnixDirectoryServiceEnum
* PoolTypeEnum
* SnapAccessLevelEnum
* SnapCreatorTypeEnum
- Unity 4.2:
* DiskTechnologyEnum
* DiskTypeEnum
- Unity 4.3:
* DatastoreTypeEnum
* ESXFilesystemMajorVersionEnum
> [GH-201]Add new HostTypeEnum

- storops/vnx/resource/port.py
- storops_test/vnx/resource/test_port.py
The issue caused unnecessary FC port registration on storage group.
A lot of setpath commands were seen in cinder volume log:
```
Apr 20 04:54:17.296339 cdh2h14 cinder-volume[21900]: INFO storops.vnx.navi_command [req-e527001b-c1f8-4c46-a819-a4883eff439e req-497f227a-9226-4ab7-81e8-af35f6413af3 tempest-VolumesSnapshotTestJSON-1661562330 None] call command: /opt/Navisphere/bin/naviseccli -h 10.228.227.225 -user sysadmin -password *** -scope global storagegroup -setpath -gname cdh2h14 -hbauid 20:00:00:24:FF:5F:27:4C:21:00:00:24:FF:5F:27:4C -sp b -spport 2 -host cdh2h14 -o
```
> Allow comparison between HbaPort and VNXSPPort

- storops/unity/parser_configs.yaml
- storops/unity/resource/system.py
- storops_test/unity/resource/test_port.py
- storops_test/unity/resource/test_system.py
- storops_test/unity/rest_data/ioLimitPolicy/burst_policy.json
- storops_test/unity/rest_data/ioLimitPolicy/index.json
added `burst_rate`,`burst_time`,`burst_frequency` parameters for
create_io_limit_policy
> [Unity]Add missing params for io limit policy

- storops/lib/converter.py
- storops/vnx/parser_configs.yaml
- storops_test/vnx/resource/test_mirror_view.py
Before this commit members of a mirror group were not listed due to wrong parsing rules. 
Additionally there are some fields that have int value but occasionally the value can be "Not Available".
For this case the "Not Available" value is parsed as -1.
> Fixed parsing of mirror group async members

- storops/exception.py
- storops/unity/resource/lun.py
- storops/unity/resource/snap.py
- storops_test/unity/resource/test_lun.py
- storops_test/unity/resource/test_snap.py
- storops_test/unity/rest_data/lun/index.json
- storops_test/unity/rest_data/lun/sv_59.json
- storops_test/unity/rest_data/snap/38654705848.json
- storops_test/unity/rest_data/snap/38654707273.json
- storops_test/unity/rest_data/snap/38654707282.json
- storops_test/unity/rest_data/snap/index.json
- storops_test/unity/rest_data/storageResource/index.json
Raise exceptions when thinclone thick luns or snaps of thick luns.
> Unity: add thick lun support

- storops/unity/resource/host.py
- storops/unity/resource/lun.py
- storops_test/unity/resource/test_lun.py
- storops_test/unity/rest_data/lun/index.json
- storops_test/unity/rest_data/lun/sv_6.json
- storops_test/unity/rest_data/lun/sv_7.json
- storops_test/unity/rest_data/storageResource/index.json
- storops_test/unity/rest_data/storageResource/sv_6.json
- storops_test/unity/rest_data/storageResource/sv_7.json
From Osprey, it supports to pass in hlu when attaching lun to host. So
storops will randomize a non-zero hlu and pass it to attach action,
which could save the `modifyHostLUN` request.
> Unity: pass in non-zero hlu when attaching

- storops/exception.py
- storops_test/unity/rest_data/storageResource/delete_sv_5605_with_thin_clone.json
The error code of deleting a lun with thinclone was wrong.
The reason is that we used the Merlin image which is not an official
one when developing thinclone feature. The official image changed the
error code.
> Unity: fix wrong error code related to thinclone

- storops/exception.py
- storops/lib/thinclone_helper.py
- storops_test/unity/resource/test_port.py
- storops_test/unity/rest_data/ioLimitPolicy/incorrect_request_body.json
- storops_test/unity/rest_data/ioLimitPolicy/index.json
- storops_test/unity/rest_data/storageResource/index.json
Bug fixes:
- Failed to create volume if qos properties include float type value (#232)
Fix: raise user friendly exception
- Failed to create volume from snapshot if qos specified (#233)
Fix: make correct request body when doing thin clone
> Bug fixes for #232 and #233

- storops/unity/resource/host.py
Unity supports maximum HLU number is 16381. So storops supports to
random pick a number from 0 to 16381 as the HLU when attaching the LUN
to host.
However, HLU number greater than 255 affects the operation of extending
an attached volume in OpenStack. The reason is that os-brick invokes
command `sg_scan` to get device information when extending volume, while
`sg_scan` uses 8 bits (maximum number is 255) to store the LUN id.
Any number greater than 255 will be truncated to wrong number via `and`
operation with `0xff`.
Thus, we need to update the range to [0 , 255].
> [GH-238] HLU number greater than 255

- storops/lib/tasks.py
The bug was reported: https://bugs.launchpad.net/cinder/+bug/1796827.
Storops supports the configured path and uses persist-queue to persist
the data to that path. However, the persist-queue is implemented to
write the data to a temp path, then leverages the atomic `os.rename` to
store the data to the user specified path.
The problem occurs when the temp path and the user specified path are on
two different devices. It raises `OSError: Invalid cross-device link`.
The fix is to make sure the temp path is no the same device of the user
specified one.
> VNX: persist queue cross device link error

- storops/unity/resource/snap.py
- storops_test/unity/resource/test_snap.py
Add a parameter to `delete` method of `UnitySnap`, which allows to force
delete the attached snapshot.
> Unity: force delete attached snapshots

- requirements.txt
In requests 2.20.0, when doing authorization, if the port of
redirect url is different from original url, the authorization
header will be dropped, already fixed and verified in latest
requests commit. So skip requests 2.20.0 in requirements.txt
> [GH-246] requests 2.20.0 issue cause storops fails to connect Unity

- storops/connection/client.py
- storops_test/connection/test_client.py
When the Unity service is unavailable, getting any resource would return
UnityResourceNotFoundError. This behavior is wrong. For example,
OpenStack checks the host existing or not before creating a new one.
Let's say the Host-1 already exists, and if the GET request is sent when
the service unavailable, the UnityResourceNotFoundError will cause
another host created with the same name.
> [GH-248] Unity:raise error if service unavailable

- storops/exception.py
- storops/unity/resource/filesystem.py
- storops_test/unity/resource/test_filesystem.py
Compare the below value before change the FS size:
used size ,
shrink size, 
current total size
> [Unity] Add exceptions for input shrink share size

- requirements.txt
Fixing #276. requests 2.22.0 is used by OpenStack.
> Remove exclusion of requests 2.22.0

- storops/unity/resource/nfs_share.py
- storops_test/unity/rest_data/nfsShare/index.json
- storops_test/unity/rest_data/storageResource/index.json
The current implementation gives a RO and ROOT access level to the share
when allow RO access right. If the ROOT access level is given, the share
will be RW finally which is not expected.
> Unity: RO share has RW access right

- storops/connection/client.py
- storops/connection/connector.py
- storops/exception.py
- storops_test/connection/test_client.py
- storops_test/connection/test_connector.py
Set the default connect timeout to 10 sec for `UnityRESTConnector`. And
raise `StoropsConnectTimeoutError` when timeout to connect to the server
using `HTTPClient`.
> Unity: add connect timeout exception

- storops/lib/metric.py
- storops/lib/parser.py
Use SafeLoader instead.
FullLoader (default loader) has exploit issue.
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
> [#264] PyYAML load warning

- storops/lib/resource.py
- storops/unity/resource/nfs_share.py
Variable cannot be named as `l`.
> Fix flask8 variable name errors

- storops/unity/client.py
- storops_test/unity/resource/test_system.py
- storops_test/unity/rest_data/lun/index.json
The filter doesn't work when having \# char in name. Need to encode it
before sending to Unity.
Use a general function `urllib.parse.quote` to encode all chars except
: and space. : and space chars are known working with Unity,
eg. hostInitiator's initiatorID is string like
iqn.1993-08.org.debian:01:a4f95ed19999 and sp name is `SP A`.
And they are massively used in test cases. So, not to encode them to
avoid introducing regression failure.
> [#307] Unity: fix url encoding

- storops/connection/client.py
- storops/unity/resource/host.py
- storops_test/unity/resource/test_host.py
Modify hlu to non-zero after attaching the snap to the host.
> Unity: skip hlu0 for snap host access

- storops/__init__.py
- storops/vnx/enums.py
- storops/vnx/heart_beat.py
- storops/vnx/resource/port.py
- storops/vnx/resource/sg.py
- storops/vnx/sg_cache.py
- storops_test/unity/resource/test_lun.py
- storops_test/vnx/cli_mock.py
- storops_test/vnx/resource/test_sg.py
- storops_test/vnx/test_enums.py
- storops_test/vnx/test_heart_beat.py
- storops_test/vnx/test_sg_cache.py
Use `persist-queue.PDict` to share the cache of storage group between
differen processes running on the same machine, i.e. different OpenStack
Cinder backends.
`PDict` leverages `pickle` to serialize and deserialize Python objects.
Objects are modified to be picklable in this commit.
> [#305] VNX: add shared cache for sg

- test-requirements.txt
Travis py36 and py37 failed because it installed incompatible
pytest(5.4.3) and pytest-xdist(2.0.0).
https://travis-ci.com/github/emc-openstack/storops/jobs/373116173, line
251, 255 and 296.
This commit just limit the version of pytest, pytest-xdist and
pytest-cov for py36 and later.
> Use compatible pytest,pytest-xdist,pytest-cov

- storops/unity/enums.py
- storops/unity/parser_configs.yaml
Unity 5.0.3 and 5.1.0 removed some deprecated fields of resources.
So, storops needs to add new fields to these resources if necessary.
Getting old fields will return `None` instead of raising
`AttributeError`. The client of storops needs to update to use new
fields.
1. `UnityHostInitiator`'s `source_type` is renamed to
`initiator_source_type`.
2. `UnityLinkAggregation`'s `parent_storage_processor` is renamed to
`storage_processor`.
3. `UnityLun`'s `is_compression_enabled` is renamed to
`is_data_reduction_enabled`.
4. Use `modification_time` to check if `UnitySnapSchedule` is modified
or not. `is_modified` is removed.
5. `UnitySystemCapacity`'s `compression_size_saved`/
`compression_percent`/`compression_ratio` is renamed to
`data_reduction_size_saved`/`data_reduction_percent`/ …
> Unity: update Unity REST 5.0.3 and 5.1.0 change

- storops/unity/resource/cifs_share.py
- storops/unity/resource/filesystem.py
- storops/unity/resource/nfs_share.py
- storops_test/unity/resource/test_cifs_share.py
- storops_test/unity/resource/test_filesystem.py
- storops_test/unity/resource/test_nfs_share.py
- storops_test/unity/rest_data/cifsShare/index.json
- storops_test/unity/rest_data/cifsShare/name_cs1_1.json
- storops_test/unity/rest_data/cifsShare/name_cs61.json
- storops_test/unity/rest_data/filesystem/fs_22.json
- storops_test/unity/rest_data/filesystem/fs_7.json
- storops_test/unity/rest_data/filesystem/index.json
- storops_test/unity/rest_data/nfsShare/index.json
- storops_test/unity/rest_data/nfsShare/name_ns1.json
- storops_test/unity/rest_data/nfsShare/name_ns1_1.json
- storops_test/unity/rest_data/nfsShare/name_ns41.json
- storops_test/unity/rest_data/storageResource/index.json
Fix filesystem, nfs share, cifs share issues:
- Incorrect response from nfs_share create() call
- Unable to remove filesystem's description
> Unity: fix fs/nfs/cifs issues

- storops/unity/resource/filesystem.py
- storops_test/unity/resource/test_filesystem.py
- storops_test/unity/rest_data/storageResource/index.json
Added snapScheduleParameters in the modify method so that snap schedule can be edited via playbook
> Added snapScheduleParameters in the modify method 
